---
title: "4.2.2CI_intensity"
author: "Huize Zhang"
date: "08/07/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(boot)

load("raw_data/court.rda")
load("raw_data/au_imputed.rda")
```


```{r}

set.seed(10000)

max.fun <- function(data,index){
    val <-  data$value[index] 
    return(max(val))
  }

boot_sim_intensity <- function(judge){
  dt <- au_imputed %>% 
    filter(judge_id == judge) %>% 
    select(judge_id: frame_id, speaker, ends_with("r")) %>% 
    gather(AU, value, -c(judge_id: speaker)) %>% 
    group_by(AU) 
    
  sim <- map(split(dt,dt$AU), function(x){
    boot.obj <- boot(x, max.fun, R = 1000)
    ci <- boot.ci(boot.obj, conf = c(0, 0.95), type = "perc")
  })
  
  temp <- map_df(sim, function(x) x$percent)
  
  sim_result <- temp[8, ] %>% 
    gather(AU, sim_low) %>% 
    left_join(temp[9, ] %>% gather(AU, sim_mean)) %>% 
    left_join(temp[10, ] %>% gather(AU, sim_high)) 
  
 
  return(sim_result)
}

judge_id = list("Keane","Gageler","Nettle","Edelman")

sim_result_int <- map_df(judge_id, function(x){
  boot_sim_intensity(x) %>% 
    mutate(judge_id = x)
  })

save(sim_result_int, file = "raw_data/sim_result.rda")


```

```{r}
load("raw_data/au_aggregate.rda")
load("raw_data/count.rda")
load("raw_data/au_video.rda")
load("raw_data/sim_result.rda")

sim_result_aug <- au_imputed %>% 
  filter(judge_id %in% c("Keane","Gageler","Nettle","Edelman")) %>% 
  select(judge_id: frame_id, speaker, ends_with("r")) %>% 
  gather(AU, value, -c(judge_id: frame_id, speaker)) %>% 
  left_join(sim_result_int) %>% 
  mutate(AU = as.factor(AU),
         outliners = as.factor(ifelse(value > sim_low, 1,0))) 

sim_result_aug %>% 
  ggplot(aes(x = sim_mean, 
             y = tidytext::reorder_within(AU, by = sim_mean, 
                                      within = judge_id, sep = "_"))) +
  geom_point(aes(x = value, col = outliners)) +
  facet_wrap(vars(judge_id), scales = "free") + 
  geom_errorbarh(aes(xmin = sim_low, xmax = sim_high), col = "gray") + 
  
  scale_y_discrete(labels = function(x) word(x, start = 1, sep = "_")) + 
  ylab("AU")

```


# Anomaly detection
```{r}

by_index <- au %>%
 filter(AU01_r != "NA") %>%
 select(AU01_r: AU45_r, judge_id: speaker) %>%
 gather(AU, value, -judge_id, -video_id) %>%
  group_by(judge_id, AU, video_id) %>% 
  nest()
  
anomaly_detection <- function(data,index){
   val <-  data$value[index]
   t = mean(val)
   val_sub <- val[-which.max(val)]
   tm = mean(val_sub)
   return(t-tm)
 }
  
model <- by_index %>% 
  mutate(bootstrap = map(data, ~boot(.x, anomaly_detection, R= 100))) %>% 
  mutate(t = map(bootstrap, ~.x$t))
  
anomaly_result <- data.frame(matrix(unlist(model$t), nrow=length(model$t), byrow=T)) %>% 
  mutate(AU = by_index$AU, judge_id = by_index$judge_id) %>% 
  gather(t_n, value, -c(AU, judge_id))

Keane <- anomaly_result %>% 
  filter(judge_id == "Keane") %>% 
  ggplot(aes(x = value)) +
  geom_density() + # bins = 3 works
  facet_wrap(vars(AU), scales = "free")

Keane


a <- anomaly_result %>% filter(judge_id == "Keane", t_n == "X1") 
a$value %>% hist()
```


