---
title: "4.2.2CI_intensity"
author: "Huize Zhang"
date: "08/07/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(purrr)
library(ggplot2)
library(boot)
library(forcats)

load("raw_data/court.rda")
load("raw_data/au.rda")
```


```{r}

set.seed(10000)

mean.fun <- function(data,index){
    val <-  data$value[index] 
    return(mean(val))
  }

boot_sim_intensity <- function(judge){
  dt <- au %>% 
    filter(judge_id ==judge, AU01_r != "NA") %>% 
    select(AU01_r: AU45_r,  judge_id : speaker) %>% 
    gather(AU, value, -c(judge_id: speaker)) %>% 
    group_by(AU) 
    
  sim <- map(split(dt,dt$AU), function(x){
    boot.obj <- boot(x, mean.fun, R = 1000)
    ci <- boot.ci(boot.obj, conf = c(0, 0.95), type = "perc")
  })
  
  temp <- map_df(sim, function(x) x$percent)
  
  sim_result <- temp[8, ] %>% 
    gather(AU, sim_low) %>% 
    left_join(temp[9, ] %>% gather(AU, sim_mean)) %>% 
    left_join(temp[10, ] %>% gather(AU, sim_high)) 
  
 
  return(sim_result)
}

au_sim_bell <- boot_sim_intensity("Bell")
au_sim_gordon <- boot_sim_intensity("Gordon") 
au_sim_gordon <- boot_sim_intensity("Gordon") 


judge_id = list("Bell","Keane","Kiefel","Gageler","Nettle","Gordon","Edelman")
sim_result_int <- map_df(judge_id, function(x){
  boot_sim_intensity(x) %>% 
    mutate(judge_id = x)
  })


```

```{r}
au_aggregate_int <- au %>% 
  filter(AU01_c != "NA") %>% 
  group_by(judge_id) %>% 
  right_join(sample_size) %>% 
  summarise_at(vars(AU01_r: AU45_r), .funs = mean) %>% 
  gather(AU, mean_agg, -judge_id) 

au_video_int <- au %>% 
  filter(AU01_c != "NA") %>% 
  select(AU01_r: AU45_r, judge_id: speaker) %>% 
  group_by(judge_id, video_id) %>% 
  summarise_at(vars(AU01_r: AU45_r), mean) %>%
  gather(AU, mean_ind, -judge_id, -video_id) %>% 
  right_join(sample_size)

count_int <- au  %>% 
  select(AU01_r: AU45_r, judge_id: speaker) %>% 
  group_by(judge_id) %>% 
  right_join(sample_size) %>%
  summarise(count = n())
```

```{r}
ci_intensity <- au_aggregate_int %>% 
  left_join(count_int) %>% 
  left_join(sim_result_int, by = c("judge_id", "AU")) %>%
  left_join(au_video_int, by = c("judge_id", "AU")) %>% 
  ungroup() %>% 
  mutate(outliners = as.factor(ifelse(mean_ind > sim_low, 
                                      ifelse(mean_ind < sim_high, 0, 1), 1)))


save(ci_intensity, file = "raw_data/ci_intensity.rda")

ci_count %>%
  mutate(AU = as.factor(AU)) %>% 
  ggplot(aes(mean_agg, AU)) + 
  geom_errorbarh(aes(xmin = sim_low, xmax = sim_high), col = "gray") + 
  facet_wrap(vars(judge_id)) + 
  geom_point(aes(x = mean_ind, y = AU, col = outliners))

```

```{r}

by_index <- au %>%
 filter(AU01_r != "NA") %>%
 select(AU01_r: AU45_r, judge_id: speaker) %>%
 gather(AU, value, -judge_id, -video_id) %>%
  group_by(judge_id, AU, video_id) %>% 
  nest()
  
anomaly_detection <- function(data,index){
   val <-  data$value[index]
   t = mean(val)
   val_sub <- val[-which.max(val)]
   tm = mean(val_sub)
   return(t-tm)
 }
  
model <- by_index %>% 
  mutate(bootstrap = map(data, ~boot(.x, anomaly_detection, R= 100))) %>% 
  mutate(t = map(bootstrap, ~.x$t))
  
anomaly_result <- data.frame(matrix(unlist(model$t), nrow=length(model$t), byrow=T)) %>% 
  mutate(AU = by_index$AU, judge_id = by_index$judge_id) %>% 
  gather(t_n, value, -c(AU, judge_id))

Keane <- anomaly_result %>% 
  filter(judge_id == "Keane") %>% 
  ggplot(aes(x = value)) +
  geom_density() + # bins = 3 works
  facet_wrap(vars(AU), scales = "free")

Keane


a <- anomaly_result %>% filter(judge_id == "Keane", t_n == "X1") 
a$value %>% hist()
```


